version: '2'
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8080"
    depends_on:
      - node1
      - node2
      - node3
    container_name: nginx
  node1:
    image: node:6.9.1
    volumes:
      - ../BackEnd_node:/src:ro
      - ../FrontEnd_ReactMobx/build:/FrontEnd_ReactMobx/build:ro
    command: [node, /src/app.js]
    container_name: node1
  node2:
    image: node:6.9.1
    volumes: 
      - ../BackEnd_node:/src:ro
      - ../FrontEnd_ReactMobx/build:/FrontEnd_ReactMobx/build:ro
    command: [node, /src/app.js]
    container_name: node2
  node3:
    image: node:6.9.1
    volumes: 
      - ../BackEnd_node:/src:ro
      - ../FrontEnd_ReactMobx/build:/FrontEnd_ReactMobx/build:ro
    command: [node, /src/app.js]
    container_name: node3

networks:
  default:
    external:
      name: my_network
